version = 3.11.3

runner.dialect = scala3
maxColumn = 120
includeCurlyBraceInSelectChains = false
project.git = true
lineEndings = preserve
align.preset = more

rewrite {
  rules = [SortModifiers, RedundantBraces, RedundantParens, PreferCurlyFors, ProcedureSyntax]
  redundantBraces.generalExpressions = false
  imports.expand = false
  trailingCommas.style = multiple
}

danglingParentheses.preset = true

rewrite.sortModifiers.order = [
  "inline",
  "private",
  "protected",
  "final",
  "sealed",
  "abstract",
  "override",
  "implicit",
  "lazy",
  "transparent",
  "opaque",
  "open"
]
