addSbtPlugin("org.scalameta"                % "sbt-scalafmt"         % "2.5.4")
addSbtPlugin("ch.epfl.scala"                % "sbt-scalafix"         % "0.14.3")
addSbtPlugin("org.typelevel"                % "sbt-tpolecat"         % "0.5.2")
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.18.33")
addSbtPlugin("se.marcuslonnberg"            % "sbt-docker"           % "1.11.0")
