addSbtPlugin("org.scalameta"                % "sbt-scalafmt"         % "2.5.6")
addSbtPlugin("ch.epfl.scala"                % "sbt-scalafix"         % "0.14.5")
addSbtPlugin("org.typelevel"                % "sbt-tpolecat"         % "0.5.2")
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen" % "0.18.46")
addSbtPlugin("com.github.sbt"               % "sbt-native-packager"  % "1.11.4")
