services:
  gateway:
    image: local/gateway-core:latest
    restart: always
#    ports:
#      - "8080:8080" # External
#      - "8081:8081" # Internal
#      - "8082:8082" # Health
#      - "8083:8083" # Docs
    environment:
      DATABASE_NAME: local_db
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: local_user
      DATABASE_PASSWORD: local_password
      EMAIL_PROVIDER_HOST: mailhog
#      APP_LOG_LEVEL: DEBUG
      EMAIL_PROVIDER_PORT: 1025
      JWT_SECRET_KEY: "Yk8zYkwwNGtVa0JvbE1NSU5lS2dtODdIMWlITzA4cDlZSkRiaFhBZmE4TT0="
      TWILIO_CLIENT_HOST: wiremock

  postgres:
    image: postgres:17.5-alpine
    restart: always
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_DB: local_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../../schemas/local/postgres:/docker-entrypoint-initdb.d

  flyway:
    image: flyway/flyway:12.0.0-alpine
    restart: on-failure
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -schemas=local_schema -connectRetries=60 migrate
    volumes:
      - ../../schemas/migrations:/flyway/sql
      - ../../schemas/local/flyway:/flyway/conf
    depends_on:
      - postgres

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: always
#    ports:
#      - "1025:1025"
#      - "8025:8025"

  wiremock:
    image: local/wiremock:latest
#    ports:
#      - "8080:8080"