package io.mesazon.waha.domain

enum WahaErrorCode {
  // Unexpected Error
  case UNEXPECTED_ERROR

  // Group Errors
  case GROUPS_GET_ERROR
  case GROUPS_GET_GROUP_ERROR
  case GROUPS_CREATE_NEW_ERROR
  case GROUPS_INVITE_CODE_ERROR
  case GROUPS_INVITE_CODE_REVOKE_ERROR
  case GROUPS_SET_DESCRIPTION_ERROR
  case GROUPS_SET_PICTURE_ERROR
  case GROUPS_SET_NAME_ERROR
  case GROUPS_DELETE_ERROR
  case GROUPS_LEAVE_ERROR
  case GROUPS_ADD_PARTICIPANT_ERROR
  case GROUPS_REMOVE_PARTICIPANT_ERROR
  case GROUPS_PROMOTE_PARTICIPANT_ERROR
  case GROUPS_DEMOTE_PARTICIPANT_ERROR
  case GROUPS_GET_PARTICIPANTS_V2_ERROR
  case GROUPS_GET_PICTURE_ERROR

  // Chatting
  case CHATTING_START_TYPING_ERROR
  case CHATTING_STOP_TYPING_ERROR
  case CHATTING_SEND_TEXT_ERROR
  case CHATTING_SEND_IMAGE_ERROR
  case CHATTING_SEND_FILE_ERROR
  case CHATTING_SEND_VOICE_ERROR
  case CHATTING_SEND_VIDEO_ERROR

  // Contacts
  case CONTACTS_CHECK_IF_EXISTS_ERROR
}
