gateway-api {
  server {
    external {
      host = "0.0.0.0"
      host = ${?SERVER_EXTERNAL_HOST}
      port = 8080
      port = ${?SERVER_EXTERNAL_PORT}
    }
    internal {
      host = "0.0.0.0"
      host = ${?SERVER_INTERNAL_HOST}
      port = 8081
      port = ${?SERVER_INTERNAL_PORT}
    }
    health {
      host = "0.0.0.0"
      host = ${?SERVER_HEALTH_HOST}
      port = 8082
      port = ${?SERVER_HEALTH_PORT}
    }
    docs {
      host = "0.0.0.0"
      host = ${?SERVER_DOCS_HOST}
      port = 8083
      port = ${?SERVER_DOCS_PORT}
    }
  }

  database {
    name = "local_db"
    name = ${?DATABASE_NAME}
    driver = "org.postgresql.Driver"
    driver = ${?DATABASE_DRIVER}
    host = "localhost"
    host = ${?DATABASE_HOST}
    port = 5432
    port = ${?DATABASE_PORT}
    username = ""
    username = ${?DATABASE_USERNAME}
    password = ""
    password = ${?DATABASE_PASSWORD}
    thread-pool-size = 20
    thread-pool-size = ${?DATABASE_THREAD_POOL_SIZE}
  }

  repository {
    schema = "local_schema"
    schema = ${?REPOSITORY_SCHEMA}
    user-onboard-table = "user_onboard"
    user-otp-table = "user_otp"
    user-details-table = "user_details"
    user-contact-table = "user_contact"
    waha-user-table = "waha_user"
    waha-user-activity-table = "waha_user_activity"
    waha-user-message-table = "waha_user_message"
  }

  validation {
    supported-regions = ["CY"]
  }

  http-client {
    connection-timeout = 10 seconds
  }

  open-ai-client {
    api-key = ""
    api-key = ${?OPENAI_API_KEY}
  }

  replying-to-messages-cron-job {
    trigger-every-seconds = 2
    trigger-every-seconds = ${?REPLYING_TO_MESSAGES_CRON_JOB_TRIGGER_EVERY_SECONDS}

    last-update-offset-seconds = 8
    last-update-offset-seconds = ${?REPLYING_TO_MESSAGES_CRON_JOB_LAST_UPDATE_OFFSET_SECONDS}

    max-number-context-messages = 40
    max-number-context-messages = ${?REPLYING_TO_MESSAGES_CRON_JOB_MAX_NUMBER_CONTEXT_MESSAGES}
  }

  waha-client {
    scheme = "http"
    scheme = ${?WAHA_SCHEME}

    host = "waha"
    host = ${?WAHA_HOST}

    port = 3000
    port = ${?WAHA_PORT}

    api-key = ""
    api-key = ${?WAHA_API_KEY}

    words-per-minute = 10000

    human-delay-min = 4 seconds

    human-delay-max = 6 seconds
  }

  email {
    host = "localhost"
    host = ${?EMAIL_PROVIDER_HOST}

    port = 1025
    port = ${?EMAIL_PROVIDER_PORT}

    sender-email = "mesazon.dev@gmail.com"
    sender-email = ${?EMAIL_SENDER_EMAIL}

    sender-password = ""
    sender-password = ${?EMAIL_SENDER_PASSWORD}

    redirect-uri = "http://localhost:1025"
    redirect-uri = ${?EMAIL_REDIRECT_URI}

    enable-tls = false
    enable-tls = ${?EMAIL_ENABLE_TLS}
  }

  authentication {
    otp-expiration = 30 seconds
    otp-expiration = ${?AUTHENTICATION_OTP_EXPIRATION}
    otp-resend-cooldown = 10 seconds
    otp-resend-cooldown = ${?AUTHENTICATION_OTP_RESEND_COOLDOWN}
    send-email-verification-email-max-retries = 5
    send-email-verification-email-max-retries = ${?AUTHENTICATION_SEND_EMAIL_VERIFICATION_EMAIL_MAX_RETRIES}
    send-email-verification-email-retry-delay = 100 milliseconds
    send-email-verification-email-retry-delay = ${?AUTHENTICATION_SEND_EMAIL_VERIFICATION_EMAIL_RETRY_DELAY}
  }
}
