gateway-api {
  server {
    external {
      host = "0.0.0.0"
      host = ${?SERVER_EXTERNAL_HOST}
      port = 8080
      port = ${?SERVER_EXTERNAL_PORT}
    }
    internal {
      host = "0.0.0.0"
      host = ${?SERVER_INTERNAL_HOST}
      port = 8081
      port = ${?SERVER_INTERNAL_PORT}
    }
    health {
      host = "0.0.0.0"
      host = ${?SERVER_HEALTH_HOST}
      port = 8082
      port = ${?SERVER_HEALTH_PORT}
    }
    docs {
      host = "0.0.0.0"
      host = ${?SERVER_DOCS_HOST}
      port = 8083
      port = ${?SERVER_DOCS_PORT}
    }
  }

  database {
    name = "local_db"
    name = ${?DATABASE_NAME}
    driver = "org.postgresql.Driver"
    driver = ${?DATABASE_DRIVER}
    host = "localhost"
    host = ${?DATABASE_HOST}
    port = 5432
    port = ${?DATABASE_PORT}
    username = ""
    username = ${?DATABASE_USERNAME}
    password = ""
    password = ${?DATABASE_PASSWORD}
    thread-pool-size = 20
    thread-pool-size = ${?DATABASE_THREAD_POOL_SIZE}
  }

  repository {
    schema = "local_schema"
    waha-users-table = "waha_users"
    waha-user-activity-table = "waha_user_activity"
    waha-user-messages-table = "waha_user_messages"
  }

  validation {
    supported-regions = ["CY"]
  }

  http-client {
    connection-timeout = 10 seconds
  }

  open-ai-client {
    api-key = ""
    api-key = ${?OPENAI_API_KEY}
  }

  replying-to-messages-cron-job {
    trigger-every-seconds = 2
    trigger-every-seconds = ${?REPLYING_TO_MESSAGES_CRON_JOB_TRIGGER_EVERY_SECONDS}

    last-update-offset-seconds = 8
    last-update-offset-seconds = ${?REPLYING_TO_MESSAGES_CRON_JOB_LAST_UPDATE_OFFSET_SECONDS}

    max-number-context-messages = 40
    max-number-context-messages = ${?REPLYING_TO_MESSAGES_CRON_JOB_MAX_NUMBER_CONTEXT_MESSAGES}
  }

  waha-client {
    scheme = "http"
    scheme = ${?WAHA_SCHEME}

    host = "waha"
    host = ${?WAHA_HOST}

    port = 3000
    port = ${?WAHA_PORT}

    api-key = ""
    api-key = ${?WAHA_API_KEY}

    words-per-minute = 10000

    human-delay-min = 3 seconds

    human-delay-max = 5 seconds
  }
}
