name: Scala PR Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'frontend/**'
  pull_request:
    paths-ignore:
        - 'docs/**'
        - 'frontend/**'
jobs:
  gateway-build:
    uses: ./.github/workflows/jobs/scala-build.yml
    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
    with:
      module: "gateway"
  gateway-publish:
    needs: ["gateway-build"]
    uses: ./.github/workflows/jobs/scala-publish.yml
    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
    with:
      module: "gateway"
