name: Gateway CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'frontend/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'frontend/**'
jobs:
  gateway-build:
    uses: ./.github/workflows/job-scala-build.yml
    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
    with:
      module: "gateway"
      docker-image-name: "mesazon-gateway-core"
  gateway-publish:
    needs: [ "gateway-build" ]
    uses: ./.github/workflows/job-publish-image.yml
    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
    with:
      docker-image-name: ${{ jobs.gateway-build.outputs.docker-image-name }}
      docker-image-tag: ${{ jobs.gateway-build.outputs.docker-image-tag }}
  gateway-deploy-dev-plan:
    needs: [ "gateway-publish" ]
    uses: ./.github/workflows/job-tf-plan.yml
    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
    with:
      project-id: "8a8c246e-2057-46b7-a01a-04cbbbf0b8d9"
      working-directory: "terraform/dev/gateway"
      module: "gateway-dev"
      docker-image-name: ${{ needs.gateway-build.outputs.docker-image-name }}
      docker-image-tag: ${{ needs.gateway-build.outputs.docker-image-tag }}
  gateway-deploy-dev-apply:
    needs: [ "gateway-deploy-dev-plan" ]
    uses: ./.github/workflows/job-tf-apply.yml
    secrets: inherit # Inherit secrets from the parent workflow https://stackoverflow.com/questions/66113900/github-actions-not-receiving-secrets
    with:
      project-id: "8a8c246e-2057-46b7-a01a-04cbbbf0b8d9"
      working-directory: "terraform/dev/gateway"
      module: "gateway-dev"
      docker-image-name: ${{ needs.gateway-build.outputs.docker-image-name }}
      docker-image-tag: ${{ needs.gateway-build.outputs.docker-image-tag }}
