name: scala-publish
on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
env:
  ENABLE_SCALA_LINT_ON_COMPILE: ${{ vars.ENABLE_SCALA_LINT_ON_COMPILE || 'false' }}
jobs:
  environment:
    name: production
  build:
    name: Build ${{ inputs.module }}
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: >
        -Xms2048M
        -Xmx2048M
        -Xss6M
        -XX:ReservedCodeCacheSize=256M
        -Dfile.encoding=UTF-8
        -XX:+UseZGC
        -XX:+ZGenerational
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_CONTAINER_REGISTRY_API_KEY }}
      - name: Login doctl
        run: doctl registry login
      - name: Build ${{ inputs.module }}-publish
        run: sbt ${{ inputs.module }}-publish
